pub mod accordion;
pub mod alert;
pub mod avatar;
pub mod badge;
pub mod button;
pub mod card;
pub mod checkbox;
pub mod divider;
pub mod dropdown;
pub mod input;
pub mod label;
pub mod list;
pub mod modal;
pub mod notification;
pub mod page_flip;
pub mod popover;
pub mod progress;
pub mod radio;
pub mod skeleton;
pub mod slider;
pub mod spinner;
pub mod switch;
pub mod tab;
pub mod text;
pub mod tooltip;

pub use accordion::*;
pub use alert::*;
pub use badge::*;
pub use button::*;
pub use checkbox::*;
pub use divider::*;
pub use input::*;
pub use label::*;
pub use page_flip::*;
pub use progress::*;
pub use radio::*;
pub use slider::*;
pub use spinner::*;
pub use switch::*;
pub use tab::*;
pub use text::*;
pub use tooltip::*;
pub use card::*;
pub use avatar::*;
pub use modal::*;
pub use notification::*;
pub use skeleton::*;
pub use popover::*;
// dropdown, list 只定义 live_design 样式

use makepad_widgets::Cx;

pub fn live_design(cx: &mut Cx) {
    crate::widgets::accordion::live_design(cx);
    crate::widgets::alert::live_design(cx);
    crate::widgets::avatar::live_design(cx);
    crate::widgets::badge::live_design(cx);
    crate::widgets::button::live_design(cx);
    crate::widgets::card::live_design(cx);
    crate::widgets::checkbox::live_design(cx);
    crate::widgets::divider::live_design(cx);
    crate::widgets::dropdown::live_design(cx);
    crate::widgets::input::live_design(cx);
    crate::widgets::label::live_design(cx);
    crate::widgets::list::live_design(cx);
    crate::widgets::modal::live_design(cx);
    crate::widgets::notification::live_design(cx);
    crate::widgets::page_flip::live_design(cx);
    crate::widgets::popover::live_design(cx);
    crate::widgets::progress::live_design(cx);
    crate::widgets::radio::live_design(cx);
    crate::widgets::skeleton::live_design(cx);
    crate::widgets::slider::live_design(cx);
    crate::widgets::spinner::live_design(cx);
    crate::widgets::switch::live_design(cx);
    crate::widgets::tab::live_design(cx);
    crate::widgets::text::live_design(cx);
    crate::widgets::tooltip::live_design(cx);
}
